packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - sharp
  - unrs-resolver

# Force consistent React versions across all packages
pnpm:
  overrides:
    - react-dom: 19.1.0
