-- Migration: Academic Structure Redesign
-- Created: 2026-01-24
-- Description: New academic structure with grade_level, class, student_enrollment, teacher_assignment

-- ============================================
-- 1. ACADEMIC YEAR TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS academic_year (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  year_name VARCHAR(20) UNIQUE NOT NULL, -- '2024-2025'
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT false,
  status VARCHAR(20) NOT NULL DEFAULT 'open', -- 'open', 'closed'
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for active academic year
CREATE INDEX idx_academic_year_active ON academic_year(is_active) WHERE is_active = true;

-- ============================================
-- 2. SEMESTER TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS semester (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  academic_year_id BIGINT NOT NULL REFERENCES academic_year(id) ON DELETE CASCADE,
  semester_name VARCHAR(10) NOT NULL, -- 'HK1', 'HK2'
  semester_number INT NOT NULL, -- 1, 2
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(academic_year_id, semester_number)
);

-- Index for active semester
CREATE INDEX idx_semester_active ON semester(is_active) WHERE is_active = true;

-- ============================================
-- 3. GRADE LEVEL TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS grade_level (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  level_name VARCHAR(20) NOT NULL UNIQUE, -- 'Khối 6', 'Khối 7'
  level_order INT NOT NULL, -- 6, 7, 8, 9
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- 4. CLASS TABLE (Updated)
-- ============================================
CREATE TABLE IF NOT EXISTS class_new (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  class_name VARCHAR(20) NOT NULL UNIQUE, -- '9A', '8B'
  academic_year_id BIGINT NOT NULL REFERENCES academic_year(id) ON DELETE CASCADE,
  grade_level_id BIGINT NOT NULL REFERENCES grade_level(id) ON DELETE CASCADE,
  homeroom_teacher_id UUID REFERENCES teachers(id) ON DELETE SET NULL, -- GVCN
  max_students INT NOT NULL DEFAULT 40,
  room_number VARCHAR(20), -- 'Phòng 201'
  status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_class_new_academic_year ON class_new(academic_year_id);
CREATE INDEX idx_class_new_grade_level ON class_new(grade_level_id);
CREATE INDEX idx_class_new_homeroom ON class_new(homeroom_teacher_id);

-- Trigger for updated_at
CREATE TRIGGER update_class_new_updated_at
  BEFORE UPDATE ON class_new
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================
-- 5. SUBJECT CATEGORY TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS subject_category (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  category_name VARCHAR(50) NOT NULL UNIQUE,
  description TEXT,
  display_order INT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed subject categories
INSERT INTO subject_category (category_name, display_order) VALUES
  ('Môn compulsory', 1),
  ('Môn tự chọn', 2),
  ('Hoạt động giáo dục', 3)
ON CONFLICT (category_name) DO NOTHING;

-- ============================================
-- 6. SUBJECT TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS subject_new (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  subject_code VARCHAR(20) NOT NULL UNIQUE, -- 'M_TOAN', 'M_VAN'
  subject_name VARCHAR(100) NOT NULL, -- 'Toán', 'Tiếng Việt'
  category_id BIGINT REFERENCES subject_category(id) ON DELETE SET NULL,
  credit_hours INT, -- Số tiết/tuần
  description TEXT,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_subject_new_category ON subject_new(category_id);
CREATE INDEX idx_subject_new_active ON subject_new(is_active) WHERE is_active = true;

-- ============================================
-- 7. STUDENT ENROLLMENT TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS student_enrollment (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  student_id UUID NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  class_id BIGINT NOT NULL REFERENCES class_new(id) ON DELETE CASCADE,
  academic_year_id BIGINT NOT NULL REFERENCES academic_year(id) ON DELETE CASCADE,
  enrollment_date DATE NOT NULL DEFAULT CURRENT_DATE,
  status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'transferred', 'graduated', 'withdrawn')),
  seat_number INT, -- Số thứ tự trong lớp
  exit_date DATE,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(student_id, class_id, academic_year_id)
);

-- Indexes
CREATE INDEX idx_enrollment_new_student ON student_enrollment(student_id);
CREATE INDEX idx_enrollment_new_class ON student_enrollment(class_id);
CREATE INDEX idx_enrollment_new_academic_year ON student_enrollment(academic_year_id);
CREATE INDEX idx_enrollment_new_status ON student_enrollment(status);

-- Trigger for updated_at
CREATE TRIGGER update_enrollment_new_updated_at
  BEFORE UPDATE ON student_enrollment
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================
-- 8. TEACHER ASSIGNMENT TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS teacher_assignment (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  teacher_id UUID NOT NULL REFERENCES teachers(id) ON DELETE CASCADE,
  class_id BIGINT NOT NULL REFERENCES class_new(id) ON DELETE CASCADE,
  subject_id BIGINT NOT NULL REFERENCES subject_new(id) ON DELETE CASCADE,
  semester_id BIGINT NOT NULL REFERENCES semester(id) ON DELETE CASCADE,
  is_active BOOLEAN NOT NULL DEFAULT true,
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(teacher_id, class_id, subject_id, semester_id)
);

-- Indexes
CREATE INDEX idx_teacher_assignment_teacher ON teacher_assignment(teacher_id);
CREATE INDEX idx_teacher_assignment_class ON teacher_assignment(class_id);
CREATE INDEX idx_teacher_assignment_subject ON teacher_assignment(subject_id);
CREATE INDEX idx_teacher_assignment_semester ON teacher_assignment(semester_id);
CREATE INDEX idx_teacher_assignment_active ON teacher_assignment(is_active) WHERE is_active = true;

-- ============================================
-- 9. GRADE TABLE (Student Academic Records)
-- ============================================
CREATE TABLE IF NOT EXISTS grade (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  student_id UUID NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  subject_id BIGINT NOT NULL REFERENCES subject_new(id) ON DELETE CASCADE,
  class_id BIGINT REFERENCES class_new(id) ON DELETE SET NULL,
  semester_id BIGINT NOT NULL REFERENCES semester(id) ON DELETE CASCADE,
  teacher_id UUID NOT NULL REFERENCES teachers(id) ON DELETE CASCADE, -- Head teacher for this subject
  assessment_type VARCHAR(20) NOT NULL, -- 'quiz', 'midterm', 'final', 'assignment'
  score DECIMAL(5,2), -- 0.00 - 10.00
  max_score DECIMAL(5,2) DEFAULT 10.00,
  grade_date DATE NOT NULL DEFAULT CURRENT_DATE,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_grade_student ON grade(student_id);
CREATE INDEX idx_grade_subject ON grade(subject_id);
CREATE INDEX idx_grade_class ON grade(class_id);
CREATE INDEX idx_grade_semester ON grade(semester_id);
CREATE INDEX idx_grade_teacher ON grade(teacher_id);
CREATE INDEX idx_grade_type ON grade(assessment_type);

-- Trigger for updated_at
CREATE TRIGGER update_grade_updated_at
  BEFORE UPDATE ON grade
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================
-- 10. ADD COLUMNS TO PROFILES
-- ============================================
-- Add student_id and parent_id to profiles for easier lookups
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS student_id UUID REFERENCES students(id) ON DELETE SET NULL;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS parent_id UUID REFERENCES parents(id) ON DELETE SET NULL;

-- Indexes for new columns
CREATE INDEX IF NOT EXISTS idx_profiles_student_id ON profiles(student_id) WHERE student_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_profiles_parent_id ON profiles(parent_id) WHERE parent_id IS NOT NULL;

-- ============================================
-- ENABLE ROW LEVEL SECURITY
-- ============================================
ALTER TABLE academic_year ENABLE ROW LEVEL SECURITY;
ALTER TABLE semester ENABLE ROW LEVEL SECURITY;
ALTER TABLE grade_level ENABLE ROW LEVEL SECURITY;
ALTER TABLE class_new ENABLE ROW LEVEL SECURITY;
ALTER TABLE subject_category ENABLE ROW LEVEL SECURITY;
ALTER TABLE subject_new ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_enrollment ENABLE ROW LEVEL SECURITY;
ALTER TABLE teacher_assignment ENABLE ROW LEVEL SECURITY;
ALTER TABLE grade ENABLE ROW LEVEL SECURITY;

-- RLS Policies (allow authenticated users to read)
CREATE POLICY "Authenticated users can read academic_year"
  ON academic_year FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can read semester"
  ON semester FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can read grade_level"
  ON grade_level FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can read class_new"
  ON class_new FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can read subject_category"
  ON subject_category FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can read subject_new"
  ON subject_new FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can read student_enrollment"
  ON student_enrollment FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can read teacher_assignment"
  ON teacher_assignment FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can read grade"
  ON grade FOR SELECT TO authenticated USING (true);
